import { type Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import MaxWidthWrapper from '@/components/MaxWidthWrapper'
import { Toaster } from "@/components/ui/sonner"
import { Providers } from "@/lib/providers"

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'TimeOffer - Time Off Management',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <Providers>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <MaxWidthWrapper>
            {children}
          </MaxWidthWrapper>
          <Toaster />
        </body>
      </html>
    </Providers>
  )
}